const PAGES_NAMES = {
  MainPage: 'MainPage',
  ActivityIndicatorPage: 'ActivityIndicatorPage',
  BadgePage: 'BadgePage',
  BottomSheetPage: 'BottomSheetPage',
  ButtonPage: 'ButtonPage',
  CardPage: 'CardPage',
  CheckBoxPage: 'CheckBoxPage',
  CheckBoxGroupPage: 'CheckBoxGroupPage',
  ChipPage: 'ChipPage',
  ChipGroupPage: 'ChipGroupPage',
  DateTimePickerPage: 'DateTimePickerPage',
  IconPage: 'IconPage',
  ImagePage: 'ImagePage',
  ModalPage: 'ModalPage',
  PageContainer: "PageContainerPage",
  RadioButtonPage: 'RadioButtonPage',
  RadioButtonGroupPage: 'RadioButtonGroupPage',
  SearchBarPage: 'SearchBarPage',
  SelectBoxPage: 'SelectBoxPage',
  SnackBarPage: 'SnackBarPage',
  SwitchPage: 'SwitchPage',
  TapSelectorPage: 'TapSelectorPage',
  TextPage: 'TextPage',
  TextInputPage: 'TextInputPage',
  SelectPage: 'SelectPage',
  ColorsPage: 'ColorsPage',
  ClassGlobalStatePage: "ClassGlobalStatePage",
  ClassExample: "ClassExample",
  StateCardPage: "StateCardPage"
};

export { PAGES_NAMES };
