const PAGES_NAMES = {
  MainPage: 'MainPage',
  TextPage: 'TextPage',
  IconPage: 'IconPage',
  TextInputPage: 'TextInputPage',
  ActivityIndicatorPage: 'ActivityIndicatorPage',
  ButtonPage: 'ButtonPage',
  TapSelectorPage: 'TapSelectorPage',
  RadioButtonPage: 'RadioButtonPage',
  RadioButtonGroupPage: 'RadioButtonGroupPage',
  CheckBoxPage: 'CheckBoxPage',
  CheckBoxGroupPage: 'CheckBoxGroupPage',
  ChipPage: 'ChipPage',
  ChipGroupPage: 'ChipGroupPage',
  BadgePage: 'BadgePage',
  ImagePage: 'ImagePage',
  SearchBarPage: 'SearchBarPage',
  ModalPage: 'ModalPage',
  SelectBoxPage: 'SelectBoxPage',
  SelectPage: 'SelectPage',
  DateTimePickerPage: 'DateTimePickerPage',
  SwitchPage: 'SwitchPage',
  ColorsPage: 'ColorsPage',
  BottomSheetPage: 'BottomSheetPage',
  SnackBarPage: 'SnackBarPage',
  CardPage: 'CardPage',
  ClassGlobalStatePage: "ClassGlobalStatePage"
};

export { PAGES_NAMES };
