import ShadowStyles from './shadow';
import type {
    IBadgeStyle,
    IButtonStyle,
    ICardStyle,
    ICheckBoxStyle,
    ICheckBoxGroupStyle,
    IChipStyle,
    IChipGroupStyle,
    IDateTimePickerStyle,
    IModalStyle,
    IPageContainerStyle,
    IRadioButtonStyle,
    IRadioButtonGroupStyle,
    ISearchBarStyle,
    ISelectBoxStyle,
    ISeperatorStyle,
    ISnackbarStyle,
    IStateCardStyle,
    ISwitchStyle,
    ITapSelectorStyle,
    ITextStyle,
    ITextInputStyle,
    CopmonentsStylesScheme
} from "./types";

import {
    badgeStyle,
    buttonStyle,
    cardStyle,
    checkBoxStyle,
    checkBoxGroupStyle,
    chipStyle,
    chipGroupStyle,
    dateTimePickerStyle,
    modalStyle,
    pageContainerStyle,
    radioButtonStyle,
    radioButtonGroupStyle,
    searchBarStyle,
    selectBoxStyle,
    seperatorStyle,
    snackbarStyle,
    stateCardStyle,
    switchStyle,
    tapSelectorStyle,
    textStyle,
    textInputStyle,
    componentsStyles
} from "./styles";

export {
    ShadowStyles,
    badgeStyle,
    buttonStyle,
    cardStyle,
    checkBoxStyle,
    checkBoxGroupStyle,
    chipStyle,
    chipGroupStyle,
    dateTimePickerStyle,
    modalStyle,
    pageContainerStyle,
    radioButtonStyle,
    radioButtonGroupStyle,
    searchBarStyle,
    selectBoxStyle,
    seperatorStyle,
    snackbarStyle,
    stateCardStyle,
    switchStyle,
    tapSelectorStyle,
    textStyle,
    textInputStyle,
    componentsStyles
};

export type {
    IBadgeStyle,
    IButtonStyle,
    ICardStyle,
    ICheckBoxStyle,
    ICheckBoxGroupStyle,
    IChipStyle,
    IChipGroupStyle,
    IDateTimePickerStyle,
    IModalStyle,
    IPageContainerStyle,
    IRadioButtonStyle,
    IRadioButtonGroupStyle,
    ISearchBarStyle,
    ISelectBoxStyle,
    ISeperatorStyle,
    ISnackbarStyle,
    IStateCardStyle,
    ISwitchStyle,
    ITapSelectorStyle,
    ITextStyle,
    ITextInputStyle,
    CopmonentsStylesScheme
}